version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach:v23.2.3
    command: start-single-node --insecure --store=attrs=ssd,path=/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  nakama:
    image: heroiclabs/nakama:3.21.0
    depends_on:
      - cockroach
    command:
      - "nakama"
      - "--config=/workspace/deploy/sandai/nakama-config.yml"
    volumes:
      - ../..:/workspace
      - ../../src/infra/runtime:/modules/sandai
    environment:
      NAKAMA_RUNTIME_PATH: /modules
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"

  sandai-api:
    build:
      context: ../..
      dockerfile: cmd/api/Dockerfile
    environment:
      SANDAI_NAKAMA_GRPC_ADDR: nakama:7349
      SANDAI_HTTP_ADDR: ":8080"
    depends_on:
      - nakama
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.50.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  cockroach-data: {}
