global:
  scrape_interval: 15s

scrape_configs:
  - job_name: sandai-api
    static_configs:
      - targets: ["sandai-api:8080"]
        labels:
          service: sandai-api
  - job_name: nakama
    static_configs:
      - targets: ["nakama:9100"]
        labels:
          service: nakama
