apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandai-api
  labels:
    app: sandai-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandai-api
  template:
    metadata:
      labels:
        app: sandai-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: api
          image: ghcr.io/sandai/api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SANDAI_HTTP_ADDR
              value: ":8080"
            - name: SANDAI_NAKAMA_GRPC_ADDR
              value: "nakama:7349"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sandai-otel
                  key: endpoint
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sandai-api
  labels:
    app: sandai-api
spec:
  type: ClusterIP
  selector:
    app: sandai-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sandai-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sandai-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sandai-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: sandai-api
